
spring:
    application:
        name: local-faby-BE

    datasource:
        url: jdbc:mysql://localhost:3306/student_tracker
        username: root
        password: adminadmin


    jpa:
        hibernate:
            ddl-auto: update
        show-sql: true
        properties:
            hibernate:
                dialect: org.hibernate.dialect.MySQL8Dialect

